_target_: data.PresetDataset
dynamics: True
data_path: /projects/collab/Human2Robot/EaseScene/robot_video/playdata.pkl
flow_length: 17
custom_epoch_len: ${epoch_size}
video_specs: 
  resize: [224, 224]
