defaults:
  - _self_
  - dataset: human
  - encoder: resnet # resnet or NULL
  - model: LinearEstimator

task: sort_screw

# train
device: cuda
distributed: false
epochs: 200
batch_size: 32
data_type: image
samplers_per_epoch: 10000
num_workers: 1

# eval
eval_subset_size: 100
eval_interval: 10
save_interval: 20


user_name: ???
job_id: ???
output_dir: outputs/${model.name}/${user_name}/${task}/${now:%Y-%m-%d}/${job_id}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: .
    subdir: . 