defaults:
  - _self_
  - policy: FlowPolicy # Diffusion, PresetPolicy, FlowPolicy
  - dataset: robot_play  # robot, preset, robot_play
  - task: sort_screw # pick_berry, sort_screw, drop_bowl

robot_data_type: execution
horizon: 12

# train: 
device: cuda
distributed: false
epochs: 600
batch_size: 64
epoch_size: 5000
num_workers: 8

use_ema: false # Set to true if using DiffusionPolicy, otherwise false
ema:
  _target_: model.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

# eval
eval_interval: 10
save_interval: 50

user_name: ??? 
job_id: ???
output_dir: outputs/${policy.name}/${user_name}/${task.task_name}/${now:%Y-%m-%d}/${job_id}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: .
    subdir: . 
