_target_: model.LinearEstimator
in_dim: 1000
train_encoder: ${encoder} #${encoder} or NULL

optimizer :
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  betas: [0.9, 0.999]
  weight_decay: 1e-2
  eps: 1e-8

name: LinearEstimator